YemekSiparis/YemekSiparis/Models/RolEkle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace YemekSiparis.Models
{
    public class RolEkle
    {
        public string RolAdi { get; set; }
    }
}

YemekSiparis/YemekSiparis/Models/RolKullaniciEkle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace YemekSiparis.Models
{
    public class RolKullaniciEkle
    {
        public string KullaniciAdi { get; set; }
        public string RolAdi { get; set; }
    }
}

YemekSiparis/YemekSiparis/Models/UrunFiyat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace YemekSiparis.Models
{
    public class UrunFiyat
    {


        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UrunFiyatID { get; set; }
        public int UrunID { get; set; }

        public int BirimID { get; set; }
        [Display(Name = "Fiyat")]
        public decimal fiyat { get; set; }
        public string imagePath { get; set; }


        public virtual Urun Urun { get; set; }
        public virtual Birim Birim { get; set; }

    }
}

YemekSiparis/YemekSiparis/Controllers/UrunFiyatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YemekSiparis.DAL;
using YemekSiparis.Models;

namespace YemekSiparis.Controllers
{
    public class UrunFiyatController : Controller
    {
        private YemekSiparisContext db = new YemekSiparisContext();

        // GET: UrunFiyat
        public ActionResult Index()
        {
            var urunFiyat = db.UrunFiyat.Include(u => u.Birim).Include(u => u.Urun);
            return View(urunFiyat.ToList());
        }

        // GET: UrunFiyat/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UrunFiyat urunFiyat = db.UrunFiyat.Find(id);
            if (urunFiyat == null)
            {
                return HttpNotFound();
            }
            return View(urunFiyat);
        }

        // GET: UrunFiyat/Create
        public ActionResult Create()
        {
            ViewBag.BirimID = new SelectList(db.Birim, "BirimID", "BirimAdi");
            ViewBag.UrunID = new SelectList(db.Urunler, "UrunID", "UrunAdi");
            return View();
        }

        // POST: UrunFiyat/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UrunFiyatID,UrunID,BirimID,fiyat,imagePath")] UrunFiyat urunFiyat)
        {
            if (ModelState.IsValid)
            {
                db.UrunFiyat.Add(urunFiyat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BirimID = new SelectList(db.Birim, "BirimID", "BirimAdi", urunFiyat.BirimID);
            ViewBag.UrunID = new SelectList(db.Urunler, "UrunID", "UrunAdi", urunFiyat.UrunID);
            return View(urunFiyat);
        }

        // GET: UrunFiyat/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UrunFiyat urunFiyat = db.UrunFiyat.Find(id);
            if (urunFiyat == null)
            {
                return HttpNotFound();
            }
            ViewBag.BirimID = new SelectList(db.Birim, "BirimID", "BirimAdi", urunFiyat.BirimID);
            ViewBag.UrunID = new SelectList(db.Urunler, "UrunID", "UrunAdi", urunFiyat.UrunID);
            return View(urunFiyat);
        }

        // POST: UrunFiyat/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UrunFiyatID,UrunID,BirimID,fiyat,imagePath")] UrunFiyat urunFiyat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urunFiyat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BirimID = new SelectList(db.Birim, "BirimID", "BirimAdi", urunFiyat.BirimID);
            ViewBag.UrunID = new SelectList(db.Urunler, "UrunID", "UrunAdi", urunFiyat.UrunID);
            return View(urunFiyat);
        }

        // GET: UrunFiyat/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UrunFiyat urunFiyat = db.UrunFiyat.Find(id);
            if (urunFiyat == null)
            {
                return HttpNotFound();
            }
            return View(urunFiyat);
        }

        // POST: UrunFiyat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UrunFiyat urunFiyat = db.UrunFiyat.Find(id);
            db.UrunFiyat.Remove(urunFiyat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YemekSiparis/YemekSiparis/Controllers/YoneticiController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YemekSiparis.DAL;
using YemekSiparis.Models;

namespace YemekSiparis.Controllers { 
   [Authorize(Roles = "Admin")]

    public class YoneticiController : Controller
    {
        private YemekSiparisContext db = new YemekSiparisContext();
        private ApplicationDbContext appDb = new ApplicationDbContext();

        // GET: UrunGrubu
        public ActionResult Index()
        {
            return View();
        }
        #region //UrunGruplari
        public ActionResult UrunGruplari()
        {
            return View(db.UrunGruplari.ToList());
        }
        public ActionResult CreateUrunGruplari()
        {
            return View("UrunGruplariCreate");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUrunGruplari([Bind(Include = "UrunGrubuID,UrunGrubuAdi")] UrunGrubu urunGrubu)
        {
            if (ModelState.IsValid)
            {
                db.UrunGruplari.Add(urunGrubu);
                db.SaveChanges();
                return RedirectToAction("UrunGruplari");
            }

            return View(urunGrubu);
        }
      
        // GET: UrunGrubu/Edit/5
        public ActionResult EditUrunGruplari(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UrunGrubu urunGrubu = db.UrunGruplari.Find(id);
            if (urunGrubu == null)
            {
                return HttpNotFound();
            }
            return View("UrunGruplariEdit", urunGrubu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUrunGruplari([Bind(Include = "UrunGrubuID,UrunGrubuAdi")] UrunGrubu urunGrubu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urunGrubu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UrunGruplari");
            }
            return View("UrunGruplariEdit", urunGrubu);
        }
        public ActionResult DeleteUrunGruplari(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UrunGrubu urunGrubu = db.UrunGruplari.Find(id);
            if (urunGrubu == null)
            {
                return HttpNotFound();
            }
            return View("UrunGruplariDelete", urunGrubu);
        }

        // POST: UrunGrubu/Delete/5
        [HttpPost, ActionName("DeleteUrunGruplari")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UrunGrubu urunGrubu = db.UrunGruplari.Find(id);
            db.UrunGruplari.Remove(urunGrubu);
            db.SaveChanges();
            return RedirectToAction("UrunGruplari");
        }
        #endregion
        #region //Urunler

        public ActionResult Urunler()
        {
            var urunler = db.Urunler.Include(u => u.UrunGrubu);
            return View("Urunler",urunler.ToList());
        }
        public ActionResult EditUrunler(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Urunler.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            ViewBag.UrunGrubuID = new SelectList(db.UrunGruplari, "UrunGrubuID", "UrunGrubuAdi", urun.UrunGrubuID);
            return View("UrunlerEdit", urun);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUrunler([Bind(Include = "UrunID,UrunGrubuID,UrunAdi")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Urunler");
            }
            ViewBag.UrunGrubuID = new SelectList(db.UrunGruplari, "UrunGrubuID", "UrunGrubuAdi", urun.UrunGrubuID);
            return View("UrunlerEdit", urun);
        }
        // GET: Urun/Create
        public ActionResult CreateUrunler()
        {
            ViewBag.UrunGrubuID = new SelectList(db.UrunGruplari, "UrunGrubuID", "UrunGrubuAdi");
            return View("UrunlerCreate");
        }

        // POST: Urun/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUrunler([Bind(Include = "UrunID,UrunGrubuID,UrunAdi")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Urunler.Add(urun);
                db.SaveChanges();
                return RedirectToAction("Urunler");
            }

            ViewBag.UrunGrubuID = new SelectList(db.UrunGruplari, "UrunGrubuID", "UrunGrubuAdi", urun.UrunGrubuID);
            return View("UrunlerCreate",urun);
        }
        public ActionResult DeleteUrunler(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Urunler.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View("UrunlerDelete",urun);
        }

        // POST: Urun/Delete/5
        [HttpPost, ActionName("DeleteUrunler")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmedForUrunler(int id)
        {
            Urun urun = db.Urunler.Find(id);
            db.Urunler.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Urunler");
        }

        #endregion
        #region //Birimler
        public ActionResult Birimler()
        {
            return View(db.Birim.ToList());
        }
        // GET: Birim/Create
        public ActionResult CreateBirimler()
        {
            return View("BirimlerCreate");
        }

        // POST: Birim/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBirimler([Bind(Include = "BirimID,BirimAdi,birimAciklama")] Birim birim)
        {
            if (ModelState.IsValid)
            {
                db.Birim.Add(birim);
                db.SaveChanges();
                return RedirectToAction("Birimler");
            }

            return View("BirimlerCreate",birim);
        }
        public ActionResult DeleteBirimler(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Birim birim = db.Birim.Find(id);
            if (birim == null)
            {
                return HttpNotFound();
            }
            return View("BirimlerDelete",birim);
        }

        // POST: Birim/Delete/5
        [HttpPost, ActionName("DeleteBirimler")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmedForBirimler(int id)
        {
            Birim birim = db.Birim.Find(id);
            db.Birim.Remove(birim);
            db.SaveChanges();
            return RedirectToAction("Birimler");
        }

        #endregion


        #region //UrunFiyat
        public ActionResult UrunFiyat()
        {
            var urunFiyat = db.UrunFiyat.Include(u => u.Birim).Include(u => u.Urun);
            return View(urunFiyat.ToList());
        }
        // GET: UrunFiyat/Create
        public ActionResult CreateUrunFiyat()
        {
            ViewBag.BirimID = new SelectList(db.Birim, "BirimID", "BirimAdi");
            ViewBag.UrunID = new SelectList(db.Urunler, "UrunID", "UrunAdi");
            return View("UrunFiyatCreate");
        }

        // POST: UrunFiyat/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUrunFiyat([Bind(Include = "UrunFiyatID,UrunID,BirimID,fiyat,imagePath")] UrunFiyat urunFiyat)
        {
            if (ModelState.IsValid)
            {
                db.UrunFiyat.Add(urunFiyat);
                db.SaveChanges();
                return RedirectToAction("UrunFiyat");
            }

            ViewBag.BirimID = new SelectList(db.Birim, "BirimID", "BirimAdi", urunFiyat.BirimID);
            ViewBag.UrunID = new SelectList(db.Urunler, "UrunID", "UrunAdi", urunFiyat.UrunID);
            return View(urunFiyat);
        }
        // GET: UrunFiyat/Edit/5
        public ActionResult EditUrunFiyat(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UrunFiyat urunFiyat = db.UrunFiyat.Find(id);
            if (urunFiyat == null)
            {
                return HttpNotFound();
            }
            ViewBag.BirimID = new SelectList(db.Birim, "BirimID", "BirimAdi", urunFiyat.BirimID);
            ViewBag.UrunID = new SelectList(db.Urunler, "UrunID", "UrunAdi", urunFiyat.UrunID);
            return View("UrunFiyatEdit",urunFiyat);
        }

        // POST: UrunFiyat/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

YemekSiparis/YemekSiparis/Views/Yonetici/Birimler.cshtml
@model IEnumerable<YemekSiparis.Models.Birim>

@{
    ViewBag.Title = "Birimler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Birimler Ekranı</h2>

<p>
    @Html.ActionLink("Yeni Birim  Oluştur", "CreateBirimler")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BirimAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.birimAciklama)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BirimAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.birimAciklama)
        </td>
        <td>          
            @Html.ActionLink("Sil", "DeleteBirimler", new { id=item.BirimID })
        </td>
    </tr>
}

</table>

YemekSiparis/YemekSiparis/Views/Yonetici/BirimlerCreate.cshtml
@model YemekSiparis.Models.Birim

@{
    ViewBag.Title = "Yeni Birim Oluşturma";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Birim Oluşturma Ekranı</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Birim Oluşturma Ekranı</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BirimAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirimAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirimAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birimAciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birimAciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birimAciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri", "Birimler")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

YemekSiparis/YemekSiparis/Views/Yonetici/Index.cshtml
@{
    ViewBag.Title = "Admin Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="jumbotron1" >
    <h1>Admin Sayfası </h1>   
</div>

YemekSiparis/YemekSiparis/Views/Yonetici/RolEkle.cshtml
@model YemekSiparis.Models.RolEkle

@{
    ViewBag.Title = "Rol Ekleme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Rol Ekleme Ekranı</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("RolEkle","Yonetici",FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group">
                @Html.LabelFor(model => model.RolAdi,  htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RolAdi, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Geri", "Roles")
    </div>
</body>
</html>

YemekSiparis/YemekSiparis/Views/Yonetici/RolKullaniciEkle.cshtml
@model YemekSiparis.Models.RolKullaniciEkle

@{
    ViewBag.Title = "Rol Ekleme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Rol Ekleme Ekranı</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("RolKullaniciEkle","Yonetici",FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group">
                @Html.LabelFor(model => model.KullaniciAdi,  htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.RolAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RolAdi, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Geri", "Roles")
    </div>
</body>
</html>

YemekSiparis/YemekSiparis/Views/Yonetici/Roles.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Roller";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Rol Ekranı</h2>

<p>
    @Html.ActionLink("Yeni Rol Oluştur", "RolEkle")
   </p> 
<p>
   @Html.ActionLink("Yeni Kullanıcı Rol Oluştur", "RolKullaniciEkle")
</p> 


<table class="table">
    <tr>
        <th>
            Rol Adı
        </th>        
        <th>Kayıtlı Kullanıcı Sayısı</th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)     
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.Count)      
            </td>
                          
        </tr>
}

</table>

YemekSiparis/YemekSiparis/Views/Yonetici/UrunFiyat.cshtml
@model IEnumerable<YemekSiparis.Models.UrunFiyat>

@{
    ViewBag.Title = "Ürün-Fiyat";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ürün-Fiyat Oluşturma Ekranı</title>
</head>
<body>
    <br />
    <br />

    <p>
        @Html.ActionLink("Yeni Ürün-Fiyat Oluştur", "CreateUrunFiyat")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Birim.BirimAdi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Urun.UrunAdi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.imagePath)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Birim.BirimAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Urun.UrunAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fiyat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.imagePath)
            </td>
            <td>
                @Html.ActionLink("Güncelle", "EditUrunFiyat", new { id=item.UrunFiyatID }) |                
                @Html.ActionLink("Sil", "DeleteUrunFiyat", new { id=item.UrunFiyatID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

YemekSiparis/YemekSiparis/Views/Yonetici/UrunFiyatDelete.cshtml
@model YemekSiparis.Models.UrunFiyat

@{
    ViewBag.Title = "Ürün-Fiyat Silme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ürün-Fiyat Silme Ekranı</title>
</head>
<body>
    <h3>Silmek istediğinizden emin misiniz?</h3>
    <div>
       <br />
        <br />
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Birim.BirimAdi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Birim.BirimAdi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Urun.UrunAdi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Urun.UrunAdi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.fiyat)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fiyat)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.imagePath)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.imagePath)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-default" /> |
                @Html.ActionLink("Geri", "UrunFiyat")
            </div>
        }
    </div>
</body>
</html>

YemekSiparis/YemekSiparis/Views/Yonetici/UrunGruplari.cshtml
@model IEnumerable<YemekSiparis.Models.UrunGrubu>

@{
    ViewBag.Title = "Ürün Çeşitleri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}
<p/>
<h2>Ürün Grupları Ekranı</h2>

<p>
    @Html.ActionLink("Yeni Ürün Grubu Oluştur", "CreateUrunGruplari", "Yonetici")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UrunGrubuAdi)         
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UrunGrubuAdi)
        </td>
        <td>
            @Html.ActionLink("Düzelt", "EditUrunGruplari", new { id=item.UrunGrubuID },"Yonetici") |
            @Html.ActionLink("Ürünler", "Details", new { id=item.UrunGrubuID }) |
            @Html.ActionLink("Sil", "DeleteUrunGruplari", new { id=item.UrunGrubuID })
        </td>
    </tr>
}

</table>